export const actionEnum=Object.freeze({
    SET_LOG_IN:0,
    LOG_IN:1,
    REGISTER:2,
    SET_USER_MESSAGE:3,
    SET_STYLE:4,
    SET_CANVAS_WIDTH:5,
    SET_DEVICE_TYPE:6,
    LOG_IN_FAILED:7,
    SET_LOGIN_INPUT:8,
    SET_PASSWORD_INPUT:9,
    SET_X_INPUT:10,
    SET_Y_INPUT:11,
    SET_R_INPUT:12,
    SET_DOTS:13
});